security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
    
    providers:
        # Utiliser une base de données pour les utilisateurs (exemple)
        users_in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            # Gérer l'authentification avec un authentificateur personnalisé
            lazy: true
            provider: users_in_database  # Assurez-vous que vous utilisez le bon fournisseur d'utilisateurs
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /app  # Redirection après déconnexion
            
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

            # activez la gestion des accès avec les rôles si nécessaire
            # activate different ways to authenticate

    access_control:
        # Contrôle d'accès pour les utilisateurs et administrateurs
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }